os: Visual Studio 2017

version: 1.1.0-{branch}-{build}

environment:
    COVERALLS_REPO_TOKEN:
       secure: taR6Lo8ItJ2wz57yn2n8wwkTuiULP+n8EicEJck1CaxeDGLWHmZzw6NX1a7RR0Cd

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - appveyor-retry dotnet restore
  
test_script:
  - dotnet test "test\Cabinet.Tests\Cabinet.Tests.csproj"

build_script:
  - ps: .\scripts\pack.ps1

after_test:
  - ps: .\scripts\coverage.ps1

artifacts:
  - path: artifacts

deploy:
  provider: NuGet
  api_key:
    secure: +AIEY0E9rURDXqzW7YM/RoRXDhOxdTZQ4XyUxNCKR6zaHvj7ha/uZHnhqofdaUu3
  skip_symbols: false
  on:
   appveyor_repo_tag: true
