version: 1.0.{build}
branches:
  only:
    - master
    - development
    - /issue-*/

environment:
    COVERALLS_REPO_TOKEN:
       secure: TODO

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

before_build:
  - nuget restore src/Cabinet.sln

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  verbosity: minimal
  project: src\Cabinet.sln
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages

after_test:
    - src\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[Cabinet*]* -[Cabinet.Tests]*" -target:"src\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"src\Halcyon.Tests\bin\Release\Halcyon.Tests.dll -appveyor -noshadow" -output:coverage.xml
    - src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover -f -r %COVERALLS_REPO_TOKEN% coverage.xml

deploy:
  provider: NuGet
  api_key:
    secure: TODO
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
   branch: master
