version: 1.0.{build}
environment:
    COVERALLS_REPO_TOKEN:
       secure: taR6Lo8ItJ2wz57yn2n8wwkTuiULP+n8EicEJck1CaxeDGLWHmZzw6NX1a7RR0Cd

cache:
  - packages -> **\packages.config

before_build:
  - nuget restore src/Cabinet.sln

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  verbosity: minimal
  project: src\Cabinet.sln
  publish_nuget: true
  publish_nuget_symbols: true

after_test:
    - src\packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[Cabinet*]* -[Cabinet.Tests]*" -target:"src\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"src\Cabinet.Tests\bin\Release\Cabinet.Tests.dll -appveyor -noshadow" -output:coverage.xml
    - src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover -f -r %COVERALLS_REPO_TOKEN% coverage.xml
nuget:
  disable_publish_on_pr: true

deploy:
  provider: NuGet
  api_key:
    secure: +AIEY0E9rURDXqzW7YM/RoRXDhOxdTZQ4XyUxNCKR6zaHvj7ha/uZHnhqofdaUu3
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
   branch: master
