version: 1.1.{build}
environment:
    COVERALLS_REPO_TOKEN:
       secure: taR6Lo8ItJ2wz57yn2n8wwkTuiULP+n8EicEJck1CaxeDGLWHmZzw6NX1a7RR0Cd

cache:
  - '%APPDATA%\npm-cache'                               # npm cache
  - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

install:
  - dnvm update-self
  - dnvm upgrade
  - dnvm upgrade -r clr
  - nuget sources add -Name https://api.nuget.org/v3/index.json -Source https://api.nuget.org/v3/index.json
  - nuget sources disable -Name nuget.org -Source https://www.nuget.org/api/v2
  - nuget sources list   # log what feeds we're using - in case of timeout
  - dnu feeds list       # log what feeds we're using - in case of timeout

before_build:
  - ps: .\version-bump.ps1
  - appveyor-retry dnu restore

build:
  verbosity: minimal
  project: Cabinet.sln
  publish_nuget: false             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages

test_script:
  - cmd: dnx -p test\Cabinet.Tests\project.json test

# "coveralls.io": "1.3.4",
# "OpenCover": "4.6.519", -- https://github.com/OpenCover/opencover/wiki/DNX-Support
#after_test:
#    - src\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[Cabinet*]* -[Cabinet.Tests]*" -target:"src\packages\xunit.runner.console.2.1.0\tools\xunit.console.exe" -targetargs:"test\Cabinet.Tests\bin\Release\Cabinet.Tests.dll -appveyor -noshadow" -output:coverage.xml
#    - src\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover --repo-token %COVERALLS_REPO_TOKEN% --full-sources coverage.xml

artifacts:
    - path: src\artifacts\bin\Cabinet\Release\*.nupkg
    - path: src\artifacts\bin\Cabinet.Mvc\Release\*.nupkg
    - path: src\artifacts\bin\Cabinet.WebApi\Release\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: +AIEY0E9rURDXqzW7YM/RoRXDhOxdTZQ4XyUxNCKR6zaHvj7ha/uZHnhqofdaUu3
  skip_symbols: false
  on:
   appveyor_repo_tag: true
